version: '3.5'

services:
  mysql:
    image: mysql:5.7.22
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --datadir=/var/lib/mysql
    container_name: mysql-5.7.22
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test.root